# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sql_foundation as sq


class Ui_CreateWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Create an item")
        MainWindow.resize(400, 300)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        MainWindow.setMaximumSize(QtCore.QSize(500, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_create_new = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_create_new.sizePolicy().hasHeightForWidth())
        self.label_create_new.setSizePolicy(sizePolicy)
        self.label_create_new.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_create_new.setObjectName("label_create_new")
        self.gridLayout.addWidget(self.label_create_new, 0, 0, 1, 1)
        self.table_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(0)
        self.table_widget.setRowCount(0)
        self.gridLayout.addWidget(self.table_widget, 1, 0, 1, 1)
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_submit.sizePolicy().hasHeightForWidth())
        self.button_submit.setSizePolicy(sizePolicy)
        self.button_submit.setObjectName("button_submit")
        self.gridLayout.addWidget(self.button_submit, 2, 0, 1, 1)
        self.button_cancel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_cancel.sizePolicy().hasHeightForWidth())
        self.button_cancel.setSizePolicy(sizePolicy)
        self.button_cancel.setObjectName("button_cancel")
        self.gridLayout.addWidget(self.button_cancel, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.connect(MainWindow)
        self.MainWindow = MainWindow
        self.tablename = None
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_create_new.setText(_translate("MainWindow", "Create new item..."))
        self.button_submit.setText(_translate("MainWindow", "Submit"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))

    def connect(self, MainWindow):
        self.button_cancel.clicked.connect(MainWindow.close)
        self.button_submit.clicked.connect(self.input_item)

    def fill_the_table(self, tablename):
        self.tablename = tablename
        columns = sq.select(
            None, tablename="information_schema.columns",
            to_select="column_name",
            cond=f"table_name = '{tablename}'",
            limit=0
        )
        self.table_widget.clear()
        self.table_widget.setColumnCount(2)
        self.table_widget.setRowCount(len(columns))
        self.table_widget.setHorizontalHeaderLabels(["Column names", "Input"])
        for i in range(len(columns)):
            item = QtWidgets.QTableWidgetItem(f"{columns[i][0]}")
            item.setFlags(item.flags() ^ QtCore.Qt.ItemIsEditable)
            self.table_widget.setItem(i, 0, item)
        self.table_widget.resizeColumnsToContents()

    def handle(self, e: Exception):
        msg = QtWidgets.QMessageBox.about(
            self.MainWindow,
            "ERROR", 
            f"Error!\n{e.args[0]}\nThe query wasn't completed"
        )        

    def input_item(self):
        connection = None
        cursor = None
        try:
            row_count = self.table_widget.rowCount()
            columns = []
            values = []
            for i in range(row_count):
                columns.append(self.table_widget.item(i, 0).text())
                value = self.table_widget.item(i, 1).text()
                if value.isdigit():
                    values.append(value)
                else:
                    values.append(f"'{value}'")
            connection = sq.ret_connection(self.handle)
            columns = sq.pack_insert_query_vals(columns)
            values = sq.pack_insert_query_vals(values)
            cursor = connection.cursor()
            cursor.execute(f"""INSERT INTO {self.tablename}{columns} VALUES{values}""")
            connection.commit()

        except Exception as e:
            self.handle(e)

        finally:
            if connection != None:
                connection.close()
            if cursor != None:
                cursor.close()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_CreateWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
