# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from sql_config import config_path


class Ui_PasswordForm(object):
    def setupUi(self, PasswordForm):
        PasswordForm.setObjectName("PasswordForm")
        PasswordForm.resize(300, 340)
        PasswordForm.setMinimumSize(QtCore.QSize(300, 340))
        PasswordForm.setMaximumSize(QtCore.QSize(300, 436))
        self.centralwidget = QtWidgets.QWidget(PasswordForm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 30))
        self.label.setMaximumSize(QtCore.QSize(200, 30))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.edit_user = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_user.sizePolicy().hasHeightForWidth())
        self.edit_user.setSizePolicy(sizePolicy)
        self.edit_user.setMinimumSize(QtCore.QSize(0, 26))
        self.edit_user.setMaximumSize(QtCore.QSize(200, 26))
        self.edit_user.setObjectName("edit_user")
        self.gridLayout.addWidget(self.edit_user, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(200, 30))
        self.label_5.setMaximumSize(QtCore.QSize(200, 30))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.edit_host = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_host.sizePolicy().hasHeightForWidth())
        self.edit_host.setSizePolicy(sizePolicy)
        self.edit_host.setMinimumSize(QtCore.QSize(0, 26))
        self.edit_host.setMaximumSize(QtCore.QSize(200, 26))
        self.edit_host.setObjectName("edit_host")
        self.gridLayout.addWidget(self.edit_host, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(200, 30))
        self.label_2.setMaximumSize(QtCore.QSize(200, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.edit_port = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_port.sizePolicy().hasHeightForWidth())
        self.edit_port.setSizePolicy(sizePolicy)
        self.edit_port.setMinimumSize(QtCore.QSize(0, 26))
        self.edit_port.setMaximumSize(QtCore.QSize(200, 26))
        self.edit_port.setObjectName("edit_port")
        self.gridLayout.addWidget(self.edit_port, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(200, 30))
        self.label_3.setMaximumSize(QtCore.QSize(200, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.edit_db_name = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_db_name.sizePolicy().hasHeightForWidth())
        self.edit_db_name.setSizePolicy(sizePolicy)
        self.edit_db_name.setMinimumSize(QtCore.QSize(0, 26))
        self.edit_db_name.setMaximumSize(QtCore.QSize(200, 26))
        self.edit_db_name.setObjectName("edit_db_name")
        self.gridLayout.addWidget(self.edit_db_name, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 30))
        self.label_4.setMaximumSize(QtCore.QSize(200, 30))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.edit_password = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_password.sizePolicy().hasHeightForWidth())
        self.edit_password.setSizePolicy(sizePolicy)
        self.edit_password.setMinimumSize(QtCore.QSize(0, 26))
        self.edit_password.setMaximumSize(QtCore.QSize(200, 26))
        self.edit_password.setObjectName("edit_password")
        self.gridLayout.addWidget(self.edit_password, 9, 0, 1, 1)
        self.spacinglabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacinglabel.sizePolicy().hasHeightForWidth())
        self.spacinglabel.setSizePolicy(sizePolicy)
        self.spacinglabel.setMinimumSize(QtCore.QSize(0, 10))
        self.spacinglabel.setMaximumSize(QtCore.QSize(0, 10))
        self.spacinglabel.setText("")
        self.spacinglabel.setObjectName("spacinglabel")
        self.gridLayout.addWidget(self.spacinglabel, 10, 0, 1, 1)
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_button.sizePolicy().hasHeightForWidth())
        self.connect_button.setSizePolicy(sizePolicy)
        self.connect_button.setMinimumSize(QtCore.QSize(100, 30))
        self.connect_button.setMaximumSize(QtCore.QSize(200, 30))
        self.connect_button.setObjectName("connect_button")
        self.gridLayout.addWidget(self.connect_button, 11, 0, 1, 1)
        self.spacinglabel_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacinglabel_2.sizePolicy().hasHeightForWidth())
        self.spacinglabel_2.setSizePolicy(sizePolicy)
        self.spacinglabel_2.setMinimumSize(QtCore.QSize(0, 10))
        self.spacinglabel_2.setMaximumSize(QtCore.QSize(0, 10))
        self.spacinglabel_2.setText("")
        self.spacinglabel_2.setObjectName("spacinglabel_2")
        self.gridLayout.addWidget(self.spacinglabel_2, 12, 0, 1, 1)
        PasswordForm.setCentralWidget(self.centralwidget)
        self.MainWindow = PasswordForm
        self.edit_password.setEchoMode(QtWidgets.QLineEdit.Password)

        self.retranslateUi(PasswordForm)
        QtCore.QMetaObject.connectSlotsByName(PasswordForm)
        self.connect()

    def retranslateUi(self, PasswordForm):
        _translate = QtCore.QCoreApplication.translate
        PasswordForm.setWindowTitle(_translate("PasswordForm", "Log in PostgreSQL"))
        self.label.setText(_translate("PasswordForm", "User"))
        self.label_5.setText(_translate("PasswordForm", "Host"))
        self.label_2.setText(_translate("PasswordForm", "Port"))
        self.label_3.setText(_translate("PasswordForm", "Database Name"))
        self.label_4.setText(_translate("PasswordForm", "Password"))
        self.connect_button.setText(_translate("PasswordForm", "Connect"))

    def connect(self):
        self.connect_button.clicked.connect(self.try_connecting)

    def handle(self, e: Exception):
        msg = QtWidgets.QMessageBox.about(
            self.MainWindow,
            "ERROR", 
            f"Error!\n{e.args[0]}\nCan't connect to database."
        )  

    def _write_cfg(self, host, port, username, db_name, password):
        from configparser import ConfigParser
        config = ConfigParser()

        config.read(config_path)
        if not config.has_section('main'):
            config.add_section('main')
        config.set('main', 'host', str(host))
        config.set('main', 'port', str(port))
        config.set('main', 'username', str(username))
        config.set('main', 'db_name', str(db_name))
        config.set('main', 'password', str(password))

        with open(config_path, 'w') as f:
            config.write(f)

    def try_connecting(self):
        try:
            import sql_foundation as sq
            hst = self.edit_host.text()
            usr = self.edit_user.text()
            db = self.edit_db_name.text()
            prt = int(self.edit_port.text())
            pwd = self.edit_password.text()
            res = sq.check_connection(
                hst, prt, usr, pwd, db
            )
            if not res:
                msg = QtWidgets.QMessageBox.about(
                    self.MainWindow,
                    "Failure",
                    "Can't connect to database."
                )
            else:
                msg = QtWidgets.QMessageBox.about(
                    self.MainWindow,
                    "Success",
                    "Connected successfully"
                )
                self._write_cfg(hst, prt, usr, db, pwd)
                self.MainWindow.close()

        except Exception as e:
            self.handle(e)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswordForm = QtWidgets.QMainWindow()
    ui = Ui_PasswordForm()
    ui.setupUi(PasswordForm)
    PasswordForm.show()
    sys.exit(app.exec_())
